### ISSUE TITLE
macOS heading font ugly (?!)

### ISSUE THREAD

**Issue by replicant64** [fundevogel/fundevogel.de#52] opened 2020-07-02 08:38 UTC
![grafik](https://user-images.githubusercontent.com/61212347/86336465-2f963480-bc50-11ea-8edd-42d520b636cd.png)

I mean whats with that man?

**Comment by S1SYPHOS** [comment] 2020-07-03 19:22
Sorry, I tested with a macOS 'High Sierra' and it looked fine - I can't reproduce this. Please check your OS' font rendering options and feel free to report back!

**Comment by replicant64** [comment] 2020-07-05 21:49
no problem, will check then

**Comment by replicant64** [comment] 2020-07-17 22:17
well it gone now, you change anything yes?

**Comment by S1SYPHOS** [comment] 2020-07-19 17:03
I tested this; it comes from our old font file. We'll fix that soon!

**Comment by S1SYPHOS** [comment] 2020-07-20 20:34
Fixed in https://github.com/fundevogel/fundevogel.de/commit/17d6b07260cd70336c0a51bd112cd102ed8d0723.

Thanks again!

**Closed as completed by S1SYPHOS** 2020-07-20 20:34 UTC
