### ISSUE TITLE
mobile header nav overlap desktop header nav

### ISSUE THREAD

**Issue by replicant64** [fundevogel/fundevogel.de#48] opened 2020-06-23 08:29 UTC
Hello,
one other thing i notice that header nav on desktop seems overlapping with normal menu, so all links are shop-links? on mac with firefox that is, chrome not!

**Comment by S1SYPHOS** [comment] 2020-07-23 07:02
Can't reproduce this, sorry.

// Edit: I was able to, eventually. I'm on it.

**Comment by replicant64** [comment] 2020-08-06 18:44
Thx man, appreciate this

**Comment by replicant64** [comment] 2020-08-06 18:50
It seems gone now, did you do something already?

**Comment by replicant64** [comment] 2020-08-09 22:41
It seems no problem now, you fixed it, yes?

**Comment by replicant64** [comment] 2020-08-20 19:43
No still there

**Comment by S1SYPHOS** [comment] 2020-08-21 06:31
I will fix it when redesigning the entire site header as this only affects users of old(er) Safari versions.

It might be reasonable though to set `display: hidden` for the time being .. thanks for staying on top of this!

**Comment by replicant64** [comment] 2020-09-01 22:26
How's that coming?

**Comment by S1SYPHOS** [comment] 2020-09-02 11:56
It needs further testing, but so far results are promising :P

**Comment by S1SYPHOS** [comment] 2020-09-03 17:18
If you'd like, we're expecting to go live tonight, feel free to test and send your feedback!

It's working for me on recent Safari versions, but who knows ..

**Comment by S1SYPHOS** [comment] 2020-09-06 17:22
As I deployed the changes last night, I'd be happy to hear from you, as it should be fixed now ..

**Comment by S1SYPHOS** [comment] 2020-09-12 10:04
I'm closing this since it seems fixed now on iOS and Safari.

**Closed as completed** 2020-09-12 10:04 UTC
Labels: bug

**Comment by replicant64** [comment] 2020-09-12 18:20
Seem is alright now, good one there!
